### ISSUE TITLE
Fix errors and add to curation database

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#19]
1. Add the manual curation at line 149 in the example.
"$ 9. Till bordläggning anmäldes:","§ 9. Till bordläggning anmäldes:"
2. Fix all train errors as manually added identified and maybe try to fix multiple errors.

**Comment by ninpnin** [comment]
What file is this in?

**Comment by MansMeg** [comment]
The one you demonstrated to me. =)

**Comment by ninpnin** [comment]
Currently, you can add rows to https://github.com/welfare-state-analytics/riksdagen-corpus/blob/dev/db/curation/manual.csv . Exact match, exact replacement.

@MansMeg your example is fixed in this commit: https://github.com/welfare-state-analytics/riksdagen-corpus/commit/5dcd98fbe9800cbc3e23c8ca6000a6e8a9cfc557
